### ISSUE TITLE
Qt6 not found

### ISSUE THREAD

**Issue by marcoferr99** [dmitry-s93/MControlCenter#229]
When i try to run `mcontrolcenter` i receive the error message:
```
mcontrolcenter: /lib/x86_64-linux-gnu/libQt6Core.so.6: version `Qt_6.8' not found (required by mcontrolcenter)
```

**Comment by shashank1010** [comment]
@marcoferr99 I totally feel you!

Dear dmitry-s93,
Dear mutchiko,

I'm sure I speak for the entire Linux/MSI community using your application when I say that we want to thank you from the bottom of our hearts for all you've done. What you and the community have created is such a huge help. Please consider adding a donation tab/button inside the app or providing information on GitHub for users to donate.

To that end, I'd like to point out an issue with the latest v0.5.0 release, which requires Qt 6.8. Even the latest Ubuntu 24.04 LTS (as verified by running 'dpkg -l | grep qt') uses Qt6.4. This is causing problems for most users.

Installing libqt6widgets6 / qt6-base **does not have any effect** since it would install Qt6.4 (even for Ubuntu 24.04/Linux Mint 22.0/22.1) ... not even to mention Debian :)

Please consider updating the latest release, making it work with Qt 6.X, but please let the app not specifically require Qt 6.8.

Sidenote: Those using eCryptfs (to encrypt their home directories) who download qt-everywhere-src-6.8.X.tar.xz will encounter additional problems during ./configure / cmake --build . --parallel, due to a hard byte limit of 143 imposed by eCryptfs on file names. This can be overcome by copying the .tar.xz into the /root directory (not using eCryptfs). After installation, Qt 6.8 will be located in /usr/local/Qt-6.8.X/, but this won't help MControlCenter to start. Users then need to install patchelf or set LD_LIBRARY_PATH to get MControlCenter 0.5.0 working with the newly installed Qt 6.8.

'sudo patchelf --set-rpath /usr/local/Qt-6.8.X/lib /bin/mcontrolcenter'

Its a total pain in the a** for normal or even slightly advanced users to get Qt6.8 installed on their system. Qt is one of the main components for the OS to run. I've spend almost a day to get this working and now that it is, it claims "ec_sys" module not found even tho it does work and find "ec_sys" if I downgrade to MControlCenter 0.4.1.

Does v0.5.0 really require Qt 6.8? Wouldn't it work with Qt 6.4?. Please reconsider this "it has to be the latest version of Qt 6.8" approach (...) and make it work out of the box for Ubuntu 24.04 / Linux Mint 22.0/22.1 users.

PS: When starting MControlCenter via the GUI and Qt 6.8 is not yet installed, no error message will be displayed. Only those running it via the terminal will come to know about the problem being an older version of Qt. Adding a "Qt 6.X not found" error popup via the GUI, when not starting the app via the terminal, would help many users understand what is actually going on.

Thanks for your time and consideration,
and thank you again for your application!

Please allow us to donate to your project.

**Comment by mutchiko** [comment]
@tschoerns can you send a screenshots of the app?

**Comment by tschoerns** [comment]
![Image](https://github.com/user-attachments/assets/f411192d-273d-4472-8322-b845f3711e67)

**Comment by mutchiko** [comment]
did you check if the driver supports your device? did you try it out before installing MCC?

**Comment by mutchiko** [comment]
okay, you tested the driver and it's working; now tell me, how did you build the app from source?

**Comment by tschoerns** [comment]
i downloaded the sourcode, unzipped it and ran "cmake MControlCenter-0.5.0".
it threw an error twice because if the two missing packages i mentioned earlier.
Once it build, i ran "cmake --build ."
thats pretty much it. 
It was my first time using cmake so i am not sure if i was supposed to change the sourcecode in any way.
QT6 i installed from the default ubuntu repository (apt install libqt6widgets6t64)

**Comment by mutchiko** [comment]
okay, to build and install the app correctly:
make sure the app is completely closed (check if there is a sys tray icon and close it)
go to the downloaded source code
open the ```scripts``` folder
open a terminal inside the folder, then run these scripts in order
1- build
2- create installer

if things went well, you should see a compressed file (send it here please), 

4- extract it.
5- open a terminal inside the new folder
6- run the **UNINSTALL** script as sudo, it might fail. thats fine
7- run the INSTALL script as sudo, the last line should be a confirmation that the install was successful.
8- check your apps, McontrolCenter should be there

**Comment by tschoerns** [comment]
i followed each step but unfortunately the result are the same. The controls are grayed out.
i attach the zip the create installer script created. 
Could be the Issue the QT6 6.4 version?

[MControlCenter-0.5.0-bin.tar.gz](https://github.com/user-attachments/files/19622246/MControlCenter-0.5.0-bin.tar.gz)

**Comment by mutchiko** [comment]
>Could be the Issue the QT6 6.4 version?

this causes other issues, but the build you sent worked fine for me, minus the messed up pages.

i need you to close the app completely (from sys tray also) and then open a terminal and type ```mcontrolcenter```, open the app's main page, return to the terminal and send the output

**Comment by tschoerns** [comment]
There is no output at all.
Not even when i switch between the tabs.

![Image](https://github.com/user-attachments/assets/9c01925f-095d-4e76-8f41-6529b3d1fb31)

**Comment by mutchiko** [comment]
i will upstream the code when i finish working on it (in a week or two), then you can build it and see if the grey controls persists, and if it is not fixed i will need you to keep testing until we get it fixed.

you need to know that if you build the app on your system this means it is not a Qt6 issue anymore, the good news is that i changed somethings that might resolve your issue.

the only solution i can give you right now is using distros that offer up to date packages like fedora/ fedora KDE and opensuse tumbleweed, or maybe arch if you feel comfortable.

**Comment by tschoerns** [comment]
Alright, thank you very much for your effort. 
I will wait and happily test the new build when it is ready.

**Comment by mutchiko** [comment]
@tschoerns please build this version from source: https://github.com/mutchiko/MControlCenter/tree/main, open an issue there if you have any problems/questions

**Comment by mutchiko** [comment]
@tschoerns go to the about page and take a screen shot

**Comment by tschoerns** [comment]
![Image](https://github.com/user-attachments/assets/d0e0a615-0566-4525-8e8c-5f67b8dde195)

**Comment by mutchiko** [comment]
this is weird, why don't you have performance mode selection?

**Comment by tschoerns** [comment]
that is a good question. i thought it might be because i disabled smart shift in the bios but enabling it does not change it. Might be something else i changed in the bios.

**Comment by mutchiko** [comment]
i know what is the problem, i'll send you a fix later, as for now, why did you disable smartshift? what other options did you modify in the bios?

**Comment by tschoerns** [comment]
i disabled smartshift because i was hoping to get better performance in a CPU heavy game. Other than that i did some undervolting. Maybe some other things but i honestly don't remember.

**Comment by tschoerns** [comment]
yep, looks good so far

![Image](https://github.com/user-attachments/assets/4b033c0e-5af5-4aac-9d45-e376d094e76b)

**Comment by tschoerns** [comment]
i did some testing and can confirm it works wonderful.
Benchmarks show a clear difference between super battery and performance.
also the fans finally go all the way up to 150%. so far they stopped at 100%
Keyboard lights are controlled by OpenRGB so no difference there. (i think the Delta 15 was "special" when it came to keyboard lights)

**Comment by mutchiko** [comment]
how did you undervolt your laptop?

**Comment by tschoerns** [comment]
in bios. i think it was called vdd18 voltage

**Comment by mutchiko** [comment]
when you change performance option in MCC, this is what changes on your laptop: 

![Image](https://github.com/user-attachments/assets/7d1730c4-b056-479f-8468-c99afe98e1e4)

if you disable smartshift, power changes won't follow EC selection, and bios will default to silent/balanced mode.

go ahead and check what values you get using RyzenCtrl

that's why i highly recommend you keep your bios at default settings at least for amd advantage laptops.

**Comment by tschoerns** [comment]
i enabled smart shift for my testing.
and now that it seems to work i leave it on. 
i only found RyzenAdjCtrl on github. is that the one you use?

**Comment by mutchiko** [comment]
yes, there is a package for arch, maybe you need to build RyzenCtrl from source because it doesn't exist on ubuntu, but it might be complicated, also that app needs a driver called RyzenAdj.

**Comment by tschoerns** [comment]
alright i build Ryzenadj and here is the output:
Performance:

![Image](https://github.com/user-attachments/assets/9d88137c-5262-4d7e-9004-a20a04db8476)

super battery:

![Image](https://github.com/user-attachments/assets/722dcbff-13b9-4626-8a95-1c2313e369a4)

at this point i would really like to thank you for your incredible effort. Just amazing that after nearly two years i finally can use the basic functions of my notebook. you rule!

**Comment by mutchiko** [comment]
Are you sure the last image was for super battery mode?

**Comment by tschoerns** [comment]
yes i confirmed it again
on silent its:
fast-limit 84
slow-limit 70
on balanced 108 and 90.

**Comment by mutchiko** [comment]
@tschoerns i noticed that you didn't have icons on the tab bar, i made some modifications that might fix that, please rebuild and reinstall: https://github.com/mutchiko/MControlCenter/tree/main?tab=readme-ov-file

**Comment by tschoerns** [comment]
fixed:

![Image](https://github.com/user-attachments/assets/5c5d5432-a970-403b-b66f-d1104edb9bba)

**Comment by tschoerns** [comment]
What i also just realized is that the tab bar is kinda broken now. 
That's how it looks like when i open the battery tab:

![Image](https://github.com/user-attachments/assets/88803106-43b5-4c51-a38a-800ef4caecc9)

**Comment by mutchiko** [comment]
@tschoerns thats why i don't support older versions of Qt, it should be fine if you build it with Qt 6.8 and up

**Comment by mutchiko** [comment]
@tschoerns if you want to test a potential fix for your issues please build from source again: https://github.com/mutchiko/MControlCenter

if you have any feedback, open an issue on THAT repo since we are beta-testing and not focusing on the main repo

**Comment by mutchiko** [comment]
for anybody still having this issue, please read the steps in the readme file, specifically how to build from source.
